# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCG2Addeditdelete():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_cG2Addeditdelete(self):
    self.driver.get("https://wcs.testly.space/atw/homepage")
    self.driver.set_window_size(1010, 708)
    self.driver.find_element(By.CSS_SELECTOR, ".home-nav-item:nth-child(6) svg").click()
    self.driver.find_element(By.LINK_TEXT, "CG2").click()
    self.driver.find_element(By.CSS_SELECTOR, ".add-button-dictionary > svg").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".add-button-dictionary > svg")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.NAME, "value").click()
    self.driver.find_element(By.NAME, "value").send_keys("1")
    self.driver.find_element(By.CSS_SELECTOR, ".footer-form > .btn-primary").click()
    self.driver.find_element(By.CSS_SELECTOR, ".MuiTableRow-root:nth-child(1) .icon-button").click()
    self.driver.find_element(By.LINK_TEXT, "Edit").click()
    self.driver.find_element(By.NAME, "value").click()
    self.driver.find_element(By.NAME, "value").send_keys("12")
    self.driver.find_element(By.CSS_SELECTOR, ".footer-form > .btn-primary").click()
    self.driver.find_element(By.CSS_SELECTOR, ".MuiTableRow-root:nth-child(1) .icon-button").click()
    self.driver.find_element(By.LINK_TEXT, "Remove").click()
    self.driver.find_element(By.CSS_SELECTOR, ".modal-footer > .btn-primary").click()
  
